# .github/configs/label-commenter-configs.yml

labels:
  - name: 'active'
    labeled:
      issue:
        body: |
          **ğŸ‰ Congratulations! Your friend link has been added.**

          Refresh the friend links page after a while to see your link.

          > If your site information changes, please directly modify the content of this issue.

          ---

          **ğŸ‰ æ­å–œï¼Œå‹é“¾æ·»åŠ æˆåŠŸï¼**

          ç¨åç‰‡åˆ»åˆ·æ–°ç½‘é¡µå°±å¯ä»¥çœ‹åˆ°æ‚¨çš„é“¾æ¥ã€‚

          > å¦‚æœæ‚¨çš„ç«™ç‚¹ä¿¡æ¯å‘ç”Ÿäº†å˜åŠ¨ï¼Œè¯·ç›´æ¥ä¿®æ”¹è¿™ä¸ª issue çš„å†…å®¹ã€‚

  - name: 'suspend'
    labeled:
      issue:
        body: |
          **ğŸ‘‹ Your friend link request has been suspended.**

          Please add our site to your friend links, and then comment below.

          ---

          **ğŸ‘‹ è¯·åŠæ—¶æ·»åŠ æœ¬ç«™å‹é“¾**

          è·ç¦»æˆåŠŸåªå‰©ä¸€æ­¥ä¹‹é¥äº†ï¼Œè¯·æŠŠæœ¬ç«™æ·»åŠ åˆ°æ‚¨çš„å‹é“¾ä¸­ï¼Œç„¶ååœ¨ä¸‹æ–¹è¯„è®ºå‘ŠçŸ¥ã€‚

  - name: '404'
    labeled:
      issue:
        body: |
          **âš ï¸ Sorry, your website is not accessible, and it has been removed from the friend links or the request has been rejected.**

          If you can confirm that your website is accessible, please comment below, and we will restore it after a manual review.

          ---

          **âš ï¸ æŠ±æ­‰ï¼Œæ‚¨çš„ç½‘ç«™æ‰“ä¸å¼€ï¼Œç°å·²ä¸‹æ¶/æ‹’ç»ç”³è¯·ã€‚**

          å¦‚æœæ‚¨ç¡®è®¤å¯ä»¥æ‰“å¼€ï¼Œè¯·åœ¨ä¸‹æ–¹è¯„è®ºå‘ŠçŸ¥ï¼Œæˆ‘ä»¬ä¼šåœ¨äººå·¥å®¡æ ¸é€šè¿‡åæ¢å¤ä¸Šæ¶ã€‚

  - name: 'not-meeting-requirements'
    labeled:
      issue:
        body: |
          **âš ï¸ Sorry, your website is missing necessary information or does not meet the requirements, and it has been removed or the request has been rejected.**

          Please make sure that:
          - You have filled in all the content in the issue template (`screenshot` is optional).
          - The JSON format of the issue content is correct and the content structure has not been modified.
          - Your website meets the requirements listed on above.

          If you can confirm that your website meets the requirements, please comment below, and we will restore it after a manual review.

          ---

          **âš ï¸ æŠ±æ­‰ï¼Œæ‚¨çš„ç½‘ç«™ç¼ºå°‘å¿…è¦ä¿¡æ¯/ä¸ç¬¦åˆè¦æ±‚ï¼Œç°å·²ä¸‹æ¶/æ‹’ç»ç”³è¯·ã€‚**

          è¯·ç¡®ä¿ï¼š
          - æ‚¨å·²å¡«å†™ issue æ¨¡æ¿ä¸­é™¤äº† `screenshot` å¤–çš„æ‰€æœ‰å†…å®¹ã€‚
          - issue åŒ…å«çš„çš„ JSON æ ¼å¼æ­£ç¡®ï¼Œä¸” issue å†…éƒ¨ç»“æ„æœªè¢«ä¿®æ”¹ã€‚
          - æ‚¨çš„ç½‘ç«™ç¬¦åˆä»¥ä¸Šåˆ—å‡ºçš„è¦æ±‚ã€‚

          å¦‚æœæ‚¨ç¡®è®¤æ‚¨çš„ç½‘ç«™ç¬¦åˆè¦æ±‚ï¼Œè¯·åœ¨ä¸‹æ–¹è¯„è®ºï¼Œæˆ‘ä»¬å°†åœ¨äººå·¥å®¡æ ¸åæ¢å¤æ‚¨çš„ç½‘ç«™ã€‚
